/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/medarbeiterTheme.ts
 * Command: astryx theme build theme/medarbeiterTheme.ts --out theme/medarbeiter.css
 * Generated: 2026-08-04T11:10:54.358Z
 */

/// <reference path="./medarbeiter.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const medarbeiterTheme: DefinedTheme;
