/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/medarbeiterTheme.ts
 * Command: astryx theme build theme/medarbeiterTheme.ts --out theme/medarbeiter.css
 * Generated: 2026-08-08T12:12:22.200Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
